name: Pain Engine CD Windows

on:
  workflow_call:

jobs:
  cd-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-release-bin
          path: bin/Release/

      - name: Prepare Installer Directory
        run: |
          $gameDir = "installer/GAMEDIRECTORY"
          if (Test-Path $gameDir) { Remove-Item -Path "$gameDir/*" -Recurse -Force -ErrorAction SilentlyContinue }
          else { New-Item -ItemType Directory -Path $gameDir }
          Copy-Item -Path "bin/Release/*" -Destination $gameDir -Recurse -Force
        shell: pwsh

      - name: Compile Installer with Inno Setup
        run: |
          & "iscc" installer/InstallScript.iss
        shell: pwsh

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Friends-Frog-ever-Installer
          path: installer/INSTALLER/Friends-Frog-ever.exe
